### ISSUE TITLE
Import Current Resources

### ISSUE THREAD

**Issue by durandguru** [vaerh/terraform-provider-routeros#2]
**Is your feature request related to a problem? Please describe.**
Is it possible to import current config from an Mikrotik to Terraform?

**Describe the solution you'd like**
If not yet available it would be nice to import current configuration, for example the current pvid settings on an bridge port.

**Additional context**

**Comment by vaerh** [comment]
Hmm, what exactly do you want to get?
Part of your request is part of the concept of Terraform [data sources](https://learn.hashicorp.com/tutorials/terraform/data-sources?in=terraform/configuration-language).
First you get the information from the data source, and then you use it as variables in resource creation.
Currently, support for 4 types of data sources: firewall, interfaces, ip addresses and routes.
```terraform
data "routeros_interfaces" "if" {
}

output "interfaces" {
  value = "${data.routeros_interfaces.if}"
}
```

Part of your request is part of the concept of Terraform [import](https://www.terraform.io/cli/commands/import).
You can import an existing bridge:
```terraform
resource "routeros_bridge" "data" {
  name      = "bridge"
}
```
```bash
terraform import routeros_bridge.data bridge
cat terraform.tfstate
```

**Comment by durandguru** [comment]
Thanks, this is wat i'm looking for. I was trying to import but I tried several options/syntax, but i missed the correct syntax ;-) It will be good to set an very basic config on the device and for all other config use terraform. Thanks for making a working version of this provider !
