### ISSUE TITLE
Send custom commands to RouterOS

### ISSUE THREAD

**Issue by iosifnicolae2** [vaerh/terraform-provider-routeros#3]
**Is your feature request related to a problem? Please describe.**
Yes, I need for example to enable the router to be a DNS server (enable `Allow Remote Requests`) and a lot of other commands.

**Describe the solution you'd like**
It would be very useful to have a resource that executes custom commands.

**Additional context**
For example:
```
resource "routeros_custom_command" "enable_dns_server" {
  create_command = "/ip dns set allow-remote-requests=yes"
  update_command  = "/ip dns set allow-remote-requests=yes"
  destroy_command  = "/ip dns set allow-remote-requests=no"
}
```

**Temporary solution**
```tf
locals {
  setup_dns_server_cmd = <<EOT
/ip dns set allow-remote-requests=yes
EOT
}
resource "null_resource" "setup_dns_server" {
  triggers = {
    on_change = local.setup_dns_server_cmd
  }
  provisioner "local-exec" {
    command = <<EOT
(ssh -T -i ${var.router.private_key_path} admin@${var.router.public_ip} <<EOF
${local.setup_dns_server_cmd}
EOF
) || exit 1
EOT
    interpreter = ["bash", "-c"]
  }
}
```

**Comment by vaerh** [comment]
Hello, sorry for the long absence. I want to take some time to think about your idea.

**Comment by vaerh** [comment]
I have considered your idea and I think there are the following problems:
1. In the TF concept, it will not be possible to allocate a unique resource ID for the integrity of which it will monitor.
2. To execute remote commands, you need to implement SSH transport, there is a basis for this, but I'm not ready to take on this global rework. Or use the execution of API/REST commands directly, but in this case, see point 1.

The implementation of the API repeats the execution of console commands. To use them, it is necessary to describe TF resources similarly to existing ones. We can jointly implement the missing resources. Adding /ip/dns won't take long.

**Comment by vaerh** [comment]
https://github.com/vaerh/terraform-provider-routeros/releases/tag/v1.1.3
